Update addvhost

diff --git a/addvhost b/addvhost
--- a/addvhost
+++ b/addvhost
@@ -4,6 +4,22 @@ OUTPUT_GREEN='\033[1;32m'
 OUTPUT_RED='\033[1;31m'
 OUTPUT_NC='\033[0m'
 
+UNDO() {
+    read -p "Do you want to undo these operations? Default y (y/n): " undo
+    if [[ -z $undo ]]; then
+        undo="y"
+    fi
+    if [[ $undo == "y" ]]; then
+        local domain="$1"
+        chattr -i /home/wwwroot/${domain}/.user.ini 2>/dev/null
+        rm -rf /home/wwwroot/"$domain"/
+        rm -f /etc/nginx/vhost/"$domain".conf
+        acme.sh --remove --domain "$domain"
+        rm -rf /root/.acme.sh/"$domain"_ecc
+        systemctl reload nginx
+    fi
+}
+
 # 验证用户输入的vhost_domain
 while true; do
     read -p "Please input your domain: " vhost_domain
@@ -91,18 +107,16 @@ if nginx -t 2>&1 | grep -q "test is successful"; then
         # 加入VHOST SSL配置项
         sed -e "s/VHOST_DOMAIN/${vhost_domain}/g" -e "s/VHOST_SUB_DOMAIN/${vhost_sub_domain}/g" /root/lnmp/vhost_ssl_1024.conf >> /etc/nginx/vhost/${vhost_domain}.conf
         sed -i "s/none.conf/${enable_wordpress}/g" /etc/nginx/vhost/${vhost_domain}.conf
+        if nginx -t 2>&1; then
+            echo -e "${OUTPUT_GREEN} Nginx configuration filev test is successful"
+        else
+            echo -e "${OUTPUT_RED} Nginx configuration filev test is fail"
+            UNDO "$vhost_domain"
+            exit 1
+        fi
         systemctl reload nginx
     else
-        read -p "Do you want to undo these operations? Default y (y/n): " undo
-        if [[ -z $undo ]]; then
-            undo="y"
-        fi
-        if [[ $undo == "y" ]]; then
-            echo -e "${OUTPUT_RED}Test http://${vhost_domain}/hello.txt failed${OUTPUT_NC}"
-            chattr -i /home/wwwroot/${vhost_domain}/.user.ini
-            rm -rf /home/wwwroot/${vhost_domain}/
-            rm -f /etc/nginx/vhost/${vhost_domain}.conf
-        fi
+        UNDO "$vhost_domain"
     fi
 else
     echo -e "${OUTPUT_RED}Nginx configuration test failed.${OUTPUT_NC}"
